import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { mtnBrighterSans } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Intern Compass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mtnBrighterSans.variable} antialiased`}>
      <body className="font-primary">{children}</body>
    </html>
  );
}
